### ISSUE TITLE
Using on production servers - Master key

### ISSUE THREAD

**Issue by ghost** [uw-labs/strongbox#47]
Love the simplicity of this.

I am curious the best practice on a server.
For example your -env file has encrypted data that was encrypted against your master key ( in $(HOME)).
When the code goes through CI and deploys, the binary needs to get the Master key from somewhere at runtime to decrypt the .env values.

Or is this not a use case envisaged ?

**Comment by george-angel** [comment]
In our case, we mount the keyring file inside the agent that deploys. Since this is plaintext, we encourage running an agent per team, as not to share keys.

**Comment by gedw99** [comment]
thanks @george-angel 
SO the agent is running on the deployment target.  What are you sing ? k8, vault ?

**Comment by george-angel** [comment]
We use https://github.com/utilitywarehouse/kube-applier

and integrate with strongbox here: https://github.com/utilitywarehouse/kube-applier/blob/master/manifests/kube-applier.yaml#L66-L81

and mount the keyring: https://github.com/utilitywarehouse/kube-applier/blob/master/manifests/kube-applier.yaml#L158-L161
