### ISSUE TITLE
strongbox.go:271: illegal base64 data at input byte 0

### ISSUE THREAD

**Issue by balupton** [uw-labs/strongbox#61]
# update

this is due to old versions inserting a `key-id` comment, which later versions do not understand, the solution is to upgrade to the latest version on a machine which has successfully decrypted the files and remove the key-id comment

# original report

I'm getting `strongbox: 2021/12/15 09:07:58 strongbox.go:271: illegal base64 data at input byte 0` after each diff via `git diff`

```
diff --git a/config.local/ddns.bash b/config.local/ddns.bash
index c520122..090ac01 100644
--- a/config.local/ddns.bash
+++ b/config.local/ddns.bash
@@ -1,6 +1,9 @@
-# STRONGBOX ENCRYPTED RESOURCE ; See https://github.com/uw-labs/strongbox
-# key-id: QaTYmvbTQD6eD1GLWwToVW213MXdK6rETebF4LZ7qHU=
-VNk/2l5RMAcRyhoHVYV7FB9ZMO3seBq1v0jb5Yo+astLMLOSzoCa/zM82Uiyhd30ncRXTpY4flgb
-8coAgdFbahIhQL5pFrIjhRp7tmmL7B94y8TYTUiW9nCJQyUoLb35+KqhpAwgcblnhdE0ybm6QoJT
-l3eW5DT5UBffGfFc6noYHaqo73cV1rLXzoyd3GnFL12HbDijJBaL99rjURqzfmihvqEC4wQwHg/q
-Qd23s4g/tRngEDRlaphn765AL2m+0MCENk1dLojm2aVWv84zmOHbX/0Zbl7EWzYlMXI=
+#!/usr/bin/env bash
+# shellcheck disable=SC2034
+# do not use `export` keyword in this file
+
+if test "$(get-hostname)" = 'raspi8'; then
+       DDNS_URL='redacted.cotunnel.com'
+       DDNS_WORKER=''
+       DDNS_WORKER_AUTH=''
+fi
strongbox: 2021/12/15 09:08:39 strongbox.go:271: illegal base64 data at input byte 0
```

Install method has been:

```
# go install -v github.com/uw-labs/strongbox@latest
# strongbox -version
version=dev commit=none date=unknown builtBy=unknown
```

**Comment by george-angel** [comment]
This happens during "checkout", when strongbox is unable to decrypt, so the key-id exists on disk, corresponding key pair is present in the keyring, but decryption fails.

Perhaps it was originally encrypted with a different key, and since you have update to a new key?

**Comment by balupton** [comment]
> Perhaps it was originally encrypted with a different key, and since you have update to a new key?

same key, not sure what happened - I ended up just rm'ing everything, committing, adding it all back, committing, then squashing, working fine now

perhaps the error message can be improved

**Comment by balupton** [comment]
This is happening everytime now on my intel mac, fresh clones fail, and removing the encrypted files and checking them out again causes the error:

```
> git clone https://github.com/balupton/dotfiles.git user
Cloning into 'user'...
remote: Enumerating objects: 7143, done.
remote: Counting objects: 100% (7143/7143), done.
remote: Compressing objects: 100% (2448/2448), done.
remote: Total 7143 (delta 4732), reused 6990 (delta 4583), pack-reused 0
Receiving objects: 100% (7143/7143), 1.25 MiB | 5.08 MiB/s, done.
Resolving deltas: 100% (4732/4732), done.
strongbox: 2022/01/10 17:59:58 strongbox.go:271: illegal base64 data at input byte 0
strongbox: 2022/01/10 17:59:58 strongbox.go:271: illegal base64 data at input byte 0
strongbox: 2022/01/10 17:59:58 strongbox.go:271: illegal base64 data at input byte 0
strongbox: 2022/01/10 17:59:58 strongbox.go:271: illegal base64 data at input byte 0
strongbox: 2022/01/10 17:59:58 strongbox.go:271: illegal base64 data at input byte 0
strongbox: 2022/01/10 17:59:58 strongbox.go:271: illegal base64 data at input byte 0
strongbox: 2022/01/10 17:59:58 strongbox.go:271: illegal base64 data at input byte 0
strongbox: 2022/01/10 17:59:58 strongbox.go:271: illegal base64 data at input byte 0
strongbox: 2022/01/10 17:59:58 strongbox.go:271: illegal base64 data at input byte 0
strongbox: 2022/01/10 17:59:58 strongbox.go:271: illegal base64 data at input byte 0
strongbox: 2022/01/10 17:59:58 strongbox.go:271: illegal base64 data at input byte 0

> cd user/

> strongbox -git-config
strongbox: 2022/01/10 18:00:02 strongbox.go:166: git global configuration updated successfully
18:00:02:/Users/balupton/.dorothy/user:master
> rm -Rf commands.local/*

> rm -Rf config.local/*


> git checkout config.local
strongbox: 2022/01/10 18:01:03 strongbox.go:271: illegal base64 data at input byte 0
strongbox: 2022/01/10 18:01:03 strongbox.go:271: illegal base64 data at input byte 0
strongbox: 2022/01/10 18:01:03 strongbox.go:271: illegal base64 data at input byte 0
strongbox: 2022/01/10 18:01:03 strongbox.go:271: illegal base64 data at input byte 0
strongbox: 2022/01/10 18:01:03 strongbox.go:271: illegal base64 data at input byte 0
strongbox: 2022/01/10 18:01:03 strongbox.go:271: illegal base64 data at input byte 0
strongbox: 2022/01/10 18:01:03 strongbox.go:271: illegal base64 data at input byte 0
strongbox: 2022/01/10 18:01:03 strongbox.go:271: illegal base64 data at input byte 0
strongbox: 2022/01/10 18:01:03 strongbox.go:271: illegal base64 data at input byte 0
strongbox: 2022/01/10 18:01:03 strongbox.go:271: illegal base64 data at input byte 0
Updated 10 paths from the index
18:01:03:/Users/balupton/.dorothy/user:master
```

**Comment by balupton** [comment]
yeah, it seems the intel mac is busted - the ubuntu machines are raspberry pi, so arm64/arm8 - perhaps that could be the issue?

**Comment by balupton** [comment]
The only thing I've noticed, is that recently there was a need for a lot of these commits on the ubuntu macs:

https://github.com/balupton/dotfiles/commit/d8746e248e7dcdbb948553221643a7976483438a

**Comment by balupton** [comment]
Maybe the ubuntu setup requires the key-id comment to be there, but the mac version reads the key-id line, instead of the blob line

**Comment by balupton** [comment]
```
# on my intel mac
> strongbox -version
version=dev commit=none date=unknown builtBy=unknown

```

```
# on my ubuntu machines
>  strongbox -version
v0.3.1
```

**Comment by george-angel** [comment]
Aha - so the `key-id` - was a failed attempt to expand the header, but the "bad" version that add the `key-id` to the header stuck around (my fault).

Please download the *latest* version, both a binary from https://github.com/uw-labs/strongbox/releases and `go get` should get you latest good version.

Then - re-encrypt all files that have `key-id` to remove it (`touch` a file should do it), and you should be okay from that point.

**Comment by balupton** [comment]
Okay, upgrading one of the ubuntu machines from v0.3.1 to latest via ` go install -v github.com/uw-labs/strongbox@latest` has broken it

**Comment by balupton** [comment]
Okay, thanks, will give that a go

**Comment by balupton** [comment]
great, that seems to have fixed it

**Comment by balupton** [comment]
Perhaps we can leave it open until the new version strips that old key-id line.

**Comment by george-angel** [comment]
@balupton there are no plans to have a version that strips key-id from the header.

There should be no version of Strongbox available that adds the `key-id` to the header now. If anyone ended up that version - they need to follow the steps you did, by pulling latest version and re-encrypting secrets.
