### ISSUE TITLE
Support in Github Actions

### ISSUE THREAD

**Issue by clarkezone** [uw-labs/strongbox#63]
Thanks for a great project.  I’m considering using it to protect a file that is needed by github action.  Is that a tested / supported scenario?

thx in advance

**Comment by george-angel** [comment]
Hey @clarkezone thanks, this is not something we have done.

I do not have much experience with Github Actions, but can you install the binary and setup via a `run` directive before checkout action?

**Comment by floriankimmel** [comment]
I used the `decrypt` command to decrypt my file after the repo has been checked out. https://github.com/floriankimmel/laufendentdecken-api/blob/main/Dockerfile. There are maybe more elegant solutions, but it worked for me.

**Comment by george-angel** [comment]
Closing - given example hopefully satisfies the use case. Thanks!
