### ISSUE TITLE
No decryption happens when clone repo to new machine despite keys in place

### ISSUE THREAD

**Issue by thisismygitrepo** [uw-labs/strongbox#69]
As described above. Despite the README file says that if keys are inplace prior to cloning, then decryption happens automatically, this is not happening on my machines. I had to do the subsequent trick of removing files then checking out again which seems an odd thing to do given that keys were in right place all the time.

Can we please reolve this inconvenience?

**Comment by george-angel** [comment]
Hey @thisismygitrepo - I'm afraid I don't observe this behaviour. Have you tried doing another clone in /tmp - to verify it happens again after you successfully got files decrypted via `checkout`? Thanks

**Comment by thisismygitrepo** [comment]
Hi G,
I just did more experiments on other machines.
So weirdly enough, everything in the repo was getting decrypted smoothly except for one folder called `.ssh`.
I just realized that everything else was decrypted successfully and the warnning messages are only related to this particular folder.

Upon cloning, this happens:
```
strongbox: 2023/01/19 12:22:48 strongbox.go:302: failed to find key id for file .ssh/authorized_keys
strongbox: 2023/01/19 12:22:48 strongbox.go:302: failed to find key id for file .ssh/config
strongbox: 2023/01/19 12:22:48 strongbox.go:302: failed to find key id for file .ssh/id_ecdsa_work
strongbox: 2023/01/19 12:22:48 strongbox.go:302: failed to find key id for file .ssh/id_ecdsa_work.pub
strongbox: 2023/01/19 12:22:48 strongbox.go:302: failed to find key id for file .ssh/id_ed25519
strongbox: 2023/01/19 12:22:48 strongbox.go:302: failed to find key id for file .ssh/id_ed25519.pub
strongbox: 2023/01/19 12:22:48 strongbox.go:302: failed to find key id for file .ssh/id_rsa
strongbox: 2023/01/19 12:22:48 strongbox.go:302: failed to find key id for file .ssh/id_rsa.pub
```

no other messages regarding other files and folders.

**Comment by george-angel** [comment]
Yes, unfortunately its a known bug and we haven't come up with a clean way of fixing it: https://github.com/uw-labs/strongbox#clone-file-ordering

**Comment by thisismygitrepo** [comment]
I see. I read the README but I didn't get it and here it is biting me so fast. So as another work around, never have files or folders that are alphabetically procedding `.strongbox-key` file. That would be a smoother work around than deletion and checkout every time. 
I also see why this is a git integration issue so getting around it can only be achieved by reconciling with git way of doing things. May I suggest of renaming the key file to something that is very unlikely to be preceeded alphabetically?

To avoid having a breaking change, one can add a catch statement for people who still have the old name and rename it automatically and support it for a year or so.

**Comment by george-angel** [comment]
Its an interesting point, and I think we have considered it when we first found this issue.

Looking at http://support.ecisolutions.com/doc-ddms/help/reportsmenu/ascii_sort_order_chart.htm the highest order char we could use without breaking most shells is `,` and keeping the file hidden we would have `.,strongbox-keyid`.

This would address a lot of cases where hidden files `.a - .s`, but it would not eliminate it.

And this would obviously break compatibility.

Sorry I'm inclined to leave behaviour as is. Another workaround is to move any affected resources a directory down the tree from the root. If you feel neither is good, it should be easy to fork and use a custom name for the keyfile.

**Comment by thisismygitrepo** [comment]
Thanks G for going through this. I will demote that folder from root directory. Please consider adding those workarounds to the README workaround section. 
I'm closing as it is a known issue.
