### ISSUE TITLE
Decrypt single resource without keyring etc

### ISSUE THREAD

**Issue by mjgarton** [uw-labs/strongbox#7]
It may be useful in some scenarios to enable decrypting a single resource, without having a keyring set up.

Examples include: build processes that don't want to create a keyring on disk and perhaps hold a single secret key as an env var.

Developers pasting something in slack to another developer who wants to just `strongbox decrypt` it.

etc.

**Comment by george-angel** [comment]
Closed by https://github.com/uw-labs/strongbox/pull/34
