### ISSUE TITLE
Trojan in the executable !!!!!!!

### ISSUE THREAD

**Issue by thisismygitrepo** [uw-labs/strongbox#70]
My windows defender caught this and I will no longer use this executable

Trojan:Win32/Wacatac.B!ml

**Comment by thisismygitrepo** [comment]
I just confirmed with virustotal that 3 vendors at least classify this executable as malicious.

**Comment by george-angel** [comment]
Hi @thisismygitrepo 

I don't know which executable you are talking about. If you downloaded a binary from https://github.com/uw-labs/strongbox/releases - they are built by Github and use GoReleaser.

If you don't trust either of those two entities, please build the binary directly from source using "go install": https://github.com/uw-labs/strongbox#installation

**Comment by thisismygitrepo** [comment]
Yes, I am referring to those binaries and you can certainly check by youself the test results on totalvirus. Closing this serious issue so fast is not a wise thing to do.
