### ISSUE TITLE
How should I store and backup my local keyring?

### ISSUE THREAD

**Issue by molleweide** [uw-labs/strongbox#71]
Hi guys,

Do you guys have any tips and pointers on how I should handle the keyring/store it?

I have gotten strongbox up and running etc. but I am curious about the best practice for handling my keyring.

**Comment by george-angel** [comment]
Hey @molleweide !

They keyring is stored in plain-text in `$HOME/.strongbox_keyring` by default.

As to backup strategies, it should be no different to how you back up your SSH or GPG keys, or any other files on your filesystem.

**Comment by molleweide** [comment]
Allright, thanks for answering!

I was suspecting that to be the answer but since I am not experienced in encryption and key management I just wanted to double check so this cleared things up for me.
