### ISSUE TITLE
`strongbox -git-config` fails on ubuntu wsl environment

### ISSUE THREAD

**Issue by balupton** [uw-labs/strongbox#77]
```
balupton@balupton-windows:~/.local/share/dorothy$ ~/.local/bin/strongbox -git-config
strongbox: 2023/10/26 15:37:10 strongbox.go:205:
balupton@balupton-windows:~/.local/share/dorothy$ ~/.local/bin/strongbox --version
version=1.1.0 commit=769068ae39b569231ee32fdfbb4ce8abc08c59f8 date=2023-01-03T13:05:25Z builtBy=goreleaser
balupton@balupton-windows:~/.local/share/dorothy$ uname -a
Linux balupton-windows 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

I downloaded `https://github.com/uw-labs/strongbox/releases/download/v1.1.0/strongbox_1.1.0_windows_amd64.exe` to `/home/balupton/.local/bin/strongbox`

**Comment by george-angel** [comment]
Hey @balupton - we don't have officially supported platforms, but anything outside of Linux and macOS is untested.

Strongbox calls `git` binary via: `exec.Command("git", command...)` - which is where you are getting an error. If `git` command is available - you might need to dig and see if there are some permission issues around `stronbox` binary trying to call `git`.
