### ISSUE TITLE
Windows Security is flagging Strongbox 2.0.0 RC exe as Phonzy.B!ml Trojan

### ISSUE THREAD

**Issue by aabmets** [uw-labs/strongbox#81]
Also, 2 software from VirusTotal detect this as malware: [LINK](https://www.virustotal.com/gui/file/37d13155423a2b27d86f6658a9bf744a5ca24bb339bae6e4cb8d42480a483948?nocache=1)

I would suggest to remedy the issue where AI heuristics falsely identify these binaries as malware.

<img src="https://github.com/user-attachments/assets/c57fc893-d4d3-4c90-ba8d-048ed2a188a3" alt="strongbox_is_malware" width="30%">

EDIT: Reduced the image dimensions to reduce white flashbang on GitHub dark theme.
Note: you can click on the image to view the original-size version in a new tab.

**Comment by george-angel** [comment]
Thanks @aabmets !

We don't actually support / test Strongbox on Windows, so I have removed that OS from the build: https://github.com/uw-labs/strongbox/pull/83

Let me know if there is anything else.

**Comment by aabmets** [comment]
@george-angel if i install GO language and run `go install` on strongbox source code, can I still use it on Windows?

**Comment by george-angel** [comment]
You can have a go, but this is not something we have tested / will support I'm afraid.
